file_format: "1"
id: elkhorn_flat_v1
name: Elkhorn Flat v1
url: https://lowprokb.ca/collections/keyboards/products/corne-ish-zen
type: board
arch: arm
features:
  - keys
outputs:
  - usb
  - ble
siblings:
  - elkhorn_flat_v1_left
  - elkhorn_flat_v1_right
