identifier: elkhorn_v2
name: Elkhorn v2
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - gpio
  - counter
  - usb_device
  - nvs
  - can
  - kscan
  - ble
  - adc
